name: CI/CD
# 触发条件
on:
  push:
    # branches:
    #   - online
    tags:
      - "v*.*.*"
    # 修改文件范围, 不在范围内不触发
    paths:
      - ".github/workflows/**"
      - "__test__/**"
      - "src/**"
# 任务
jobs:
  test:
    # 运行的基础
    runs-on: ubuntu-latest
    environment: test
    # 步骤
    steps:
      - uses: actions/checkout@v3 # git pull
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: 打包镜像, 上传 Docker Hub
        run: |
          echo '${{ secrets.REGISTRY_PASSWORD }}'
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build --platform linux/amd64 -t vite-ssg:latest .
          docker tag vite-ssg:latest ${{ secrets.DOCKER_REPOSITORY }}
          docker push ${{ secrets.DOCKER_REPOSITORY }}
      - name: 登录服务器, 执行脚本
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASSWORD }}
          # 执行脚本
          script: |
            docker pull ${{ secrets.DOCKER_REPOSITORY }}
            docker stop vite-ssg
            docker rm vite-ssg
            docker run --name vite-ssg -d -p 9090:80 ${{ secrets.DOCKER_REPOSITORY }}
            docker image prune -f --filter "until=24h"
            docker container prune -f --filter "until=24h"
